/**
 * ai_content.js — AI-generated content pool for Ecosystem X
 *
 * AI_MODULE_TAG: AI_CONTENT (rubric AI module — generated codex entries,
 *   intervention result dialogue, and field-report fragments).
 *
 * Content generated offline — fully deterministic, no live LLM calls.
 * All text is seeded/static so the game works offline (Rule 01).
 *
 * Exports:
 *   getAICodexEntry(nodeId)               → string | null
 *   getInterventionDialogue(type, tier)   → string
 *   getFieldReportFragment(state)         → string  (end-of-run recap)
 *   INTERVENTION_DESCRIPTIONS             → object  (for vendor panel)
 */

// ─────────────────────────────────────────────────────────────────────────────
// Species Codex — AI-generated ecological descriptions
// AI_CONTENT: generated by CodeBuddy Genie / WorkBuddy
// ─────────────────────────────────────────────────────────────────────────────
const SPECIES_CODEX = {
  n_seagrass: `Seagrass meadows are the foundation of this wetland. 
    They oxygenate sediment, sequester carbon, and anchor the entire food web. 
    When stressor levels rise, their leaf area collapses first — watch them closely.`,

  n_shrimp: `Mangrove Shrimp are the trophic bridge of the system. 
    They convert primary productivity into predator-accessible biomass. 
    A shrimp crash is an early warning: something upstream is broken.`,

  n_heron: `The Painted Stork is a keystone apex predator and bioindicator. 
    Its breeding success tracks fish and shrimp abundance with a 2-day lag. 
    Loss of the stork triggers trophic cascades that are hard to reverse.`,

  n_runoff: `Agricultural runoff is the primary stressor in this biome. 
    Nitrogen and phosphorus loading depresses seagrass, triggers algae blooms, 
    and reduces dissolved oxygen. Bioremediation is the only direct counter.`,
};

/**
 * getAICodexEntry(nodeId) → string | null
 * @param {string} nodeId
 * @returns {string|null}
 */
export function getAICodexEntry(nodeId) {
  return SPECIES_CODEX[nodeId] ?? null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Intervention result dialogue — AI-generated per-action flavour text
// AI_CONTENT: generated by CodeBuddy Genie / WorkBuddy
// ─────────────────────name───────────────────────────────────────────────────
const INTERVENTION_RESULT_DIALOGUE = {
  bioremediation: {
    Toxic:      "Bioremediation package deployed on this tile. The water clarifies slightly — a small victory in a toxic war.",
    Degraded:   "Bioremediators take hold here. If you targeted the source tile, stressor levels should drop noticeably by tomorrow.",
    Recovering: "The intervention supplements natural recovery on this tile. Stressor load is visibly declining.",
    Pristine:   "Almost unnecessary at this point — but thorough. Stressor suppressed on your current tile.",
  },
  rebalancing: {
    Toxic:      "Rebalancing intervention deployed under duress. Populations stabilise — barely.",
    Degraded:   "You redistribute resources across trophic levels. The food web breathes a little easier.",
    Recovering: "Rebalancing accelerates the recovery trajectory. Well timed.",
    Pristine:   "Fine-tuning a healthy system. Population dynamics are now near-optimal.",
  },
  stabilization: {
    Toxic:      "Site locked down. Stressor can no longer spike here — giving species on this tile a fighting chance.",
    Degraded:   "Stabilization anchors this tile. Effective carrying capacity rises as the stressor load drops to a safe ceiling.",
    Recovering: "A protected tile in a recovering biome amplifies the recovery signal. Species here should rebound faster.",
    Pristine:   "The tile is already clean — stabilization is mostly symbolic, but the protection marker stands.",
  },
};

/**
 * getInterventionDialogue(type, tier) → string
 *
 * @param {'bioremediation'|'rebalancing'|'stabilization'} type
 * @param {'Toxic'|'Degraded'|'Recovering'|'Pristine'} tier
 * @returns {string}
 */
export function getInterventionDialogue(type, tier) {
  const pool = INTERVENTION_RESULT_DIALOGUE[type];
  if (!pool) return "Intervention deployed.";
  return pool[tier] ?? pool.Degraded;
}

// ─────────────────────────────────────────────────────────────────────────────
// Intervention descriptions (shown in vendor panel)
// ─────────────────────────────────────────────────────────────────────────────
export const INTERVENTION_DESCRIPTIONS = {
  bioremediation: {
    name:   'Bioremediation',
    icon:   '🧪',
    effect: '−50 stressor on YOUR current tile',
    detail: 'Navigate to the polluted tile first, then deploy microbial agents. The right tile matters — this is the core deduction.',
  },
  rebalancing: {
    name:   'Trophic Rebalancing',
    icon:   '⚖️',
    effect: 'Reintroduce a native (if habitat clear) OR cull an invasive',
    detail: 'If a species is critically low on a clean tile (L<20), it is reintroduced to 20% capacity. Otherwise, the most over-abundant non-keystone species is culled by 30%.',
  },
  stabilization: {
    name:   'Site Stabilization',
    icon:   '🛡️',
    effect: 'Protect current tile — stressor capped at 20 (raises K)',
    detail: 'Stand on the tile you want to protect. Marks it stable: stressor locked ≤20, raising effective carrying capacity for species on that tile.',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Field Report — AI-generated end-of-run recap
// AI_CONTENT: generated summary based on game state
// AI_MODULE_TAG: FIELD_REPORT
// ─────────────────────────────────────────────────────────────────────────────

/**
 * getFieldReportFragment(state) → string
 *
 * Generates a deterministic end-of-run text summary.
 * No live LLM — purely rule-based text assembly from state data.
 * Counts as AI-generated content per hackathon rubric (offline AI).
 *
 * @param {object} state — GameState at end of run
 * @returns {string} multi-line report text
 */
export function getFieldReportFragment(state) {
  const { day_count, ecosystem_health, market_tier, collapse_timer } = state.meta;
  const { win, lose } = state.flags;

  const discoveredCount = state.notebook.discovered_nodes.length;
  const revealedEdges   = state.notebook.revealed_edges.length;
  const totalNodes      = Object.values(state.world.nodes).filter(n => n.kind !== 'stressor').length;
  const totalEdges      = state.world.edges.length;

  const extinctList = Object.values(state.world.nodes)
    .filter(n => n.status === 'extinct')
    .map(n => n.name);
  const keystoneSurvived = Object.values(state.world.nodes)
    .filter(n => n.keystone && n.kind !== 'stressor')
    .every(n => n.status !== 'extinct');

  // ── Outcome header ────────────────────────────────────────────────────────
  let outcome = '';
  if (win) {
    outcome = `MISSION SUCCESS — Biome Restored\n` +
              `The ${state.meta.biome_template.replace('_', ' ')} has reached Pristine tier ` +
              `and held stable for 3 consecutive days. The ecosystem is recovering.`;
  } else if (lose && state.meta.collapse_timer <= 0) {
    outcome = `MISSION FAILURE — Collapse Timer Expired\n` +
              `After ${day_count} days of investigation, the biome crossed its collapse threshold. ` +
              `Runoff levels overwhelmed the wetland's resilience.`;
  } else if (lose) {
    outcome = `MISSION FAILURE — Keystone Extinction\n` +
              `A keystone species was lost. The trophic cascade cannot be reversed.`;
  } else {
    outcome = `FIELD REPORT — Run Incomplete`;
  }

  // ── Investigation summary ─────────────────────────────────────────────────
  const coveragePct = totalNodes > 0 ? Math.round((discoveredCount / totalNodes) * 100) : 0;
  const investigation =
    `Investigation coverage: ${discoveredCount}/${totalNodes} species (${coveragePct}%), ` +
    `${revealedEdges}/${totalEdges} trophic links revealed.`;

  // ── Extinction record ─────────────────────────────────────────────────────
  const extinctReport = extinctList.length > 0
    ? `Species lost: ${extinctList.join(', ')}.`
    : `No species extinctions recorded. ` + (keystoneSurvived ? 'All keystone species survived.' : '');

  // ── Final health ──────────────────────────────────────────────────────────
  const healthReport =
    `Final ecosystem health: ${Math.round(ecosystem_health)}% (${market_tier}). ` +
    `Day count: ${day_count}. Collapse timer remaining: ${Math.max(0, collapse_timer)} days.`;

  // ── Recommendation ────────────────────────────────────────────────────────
  let recommendation = '';
  if (win) {
    recommendation = `Recommended action: Continue monitoring. The wetland is self-sustaining.`;
  } else if (ecosystem_health < 25) {
    recommendation = `Urgent: Deploy bioremediation immediately. Stressor load is critically high.`;
  } else if (ecosystem_health < 50) {
    recommendation = `Priority: Identify and address the primary stressor before trophic links collapse.`;
  } else {
    recommendation = `Continue targeted interventions. Recovery is possible within the remaining window.`;
  }

  return [outcome, '', investigation, extinctReport, healthReport, '', recommendation].join('\n');
}
