/**
 * ai_content.js — AI-generated content pool for Ecosystem X
 *
 * AI_MODULE_TAG: AI_CONTENT (rubric AI module — generated codex entries,
 *   intervention result dialogue, and field-report fragments).
 *
 * Content generated offline — fully deterministic, no live LLM calls.
 * All text is seeded/static so the game works offline (Rule 01).
 *
 * External JSON files (data/) are loaded at boot via loadAIContent().
 * On any fetch error the inline constants below are the OFFLINE FALLBACK
 * (Rule 01 — game must still run if a file is missing).
 *
 * Exports:
 *   loadAIContent()                       → Promise<void>  (call once at boot)
 *   getAICodexEntry(nodeId)               → string | null
 *   getInterventionDialogue(type, tier)   → string
 *   getFieldReportFragment(state)         → string  (end-of-run recap)
 *   INTERVENTION_DESCRIPTIONS             → object  (for vendor panel)
 */

// ─────────────────────────────────────────────────────────────────────────────
// Module-level cache — populated by loadAIContent(); null = not yet loaded
// ─────────────────────────────────────────────────────────────────────────────
let _loadedCodex     = null;   // keyed by node id → string
let _loadedFragments = null;   // keyed by situation key → string[]

// ─────────────────────────────────────────────────────────────────────────────
// Species Codex — OFFLINE FALLBACK
// AI_CONTENT: generated by CodeBuddy Genie / WorkBuddy
// ─────────────────────────────────────────────────────────────────────────────
const SPECIES_CODEX = {
  n_seagrass: `Seagrass meadows are the foundation of this wetland. 
    They oxygenate sediment, sequester carbon, and anchor the entire food web. 
    When stressor levels rise, their leaf area collapses first — watch them closely.`,

  n_shrimp: `Mangrove Shrimp are the trophic bridge of the system. 
    They convert primary productivity into predator-accessible biomass. 
    A shrimp crash is an early warning: something upstream is broken.`,

  n_heron: `The Painted Stork is a keystone apex predator and bioindicator. 
    Its breeding success tracks fish and shrimp abundance with a 2-day lag. 
    Loss of the stork triggers trophic cascades that are hard to reverse.`,

  n_runoff: `Agricultural runoff is the primary stressor in this biome. 
    Nitrogen and phosphorus loading depresses seagrass, triggers algae blooms, 
    and reduces dissolved oxygen. Bioremediation is the only direct counter.`,
};

// ─────────────────────────────────────────────────────────────────────────────
// loadAIContent() — fetch JSON files once at boot; keep fallbacks on error
// ─────────────────────────────────────────────────────────────────────────────

/**
 * loadAIContent() → Promise<void>
 *
 * Fetches data/codex.json and data/report-fragments.json.
 * On success, caches them in module-level vars.
 * On any error (network, parse, missing file), silently keeps inline fallbacks.
 * Safe to call multiple times — re-fetches only if not yet loaded.
 */
export async function loadAIContent() {
  // Codex
  try {
    const resp = await fetch('data/codex.json');
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    const json = await resp.json();
    if (json && typeof json === 'object') {
      _loadedCodex = json;
      console.log('[ai_content] codex.json loaded:', Object.keys(json).length, 'entries');
    }
  } catch (err) {
    console.warn('[ai_content] codex.json unavailable — using inline fallback.', err.message);
  }

  // Report fragments
  try {
    const resp = await fetch('data/report-fragments.json');
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    const json = await resp.json();
    if (json && typeof json === 'object') {
      _loadedFragments = json;
      console.log('[ai_content] report-fragments.json loaded:', Object.keys(json).length, 'keys');
    }
  } catch (err) {
    console.warn('[ai_content] report-fragments.json unavailable — using inline fallback.', err.message);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// getAICodexEntry — returns loaded JSON entry if present, else inline fallback
// ─────────────────────────────────────────────────────────────────────────────

/**
 * getAICodexEntry(nodeId) → string | null
 * @param {string} nodeId
 * @returns {string|null}
 */
export function getAICodexEntry(nodeId) {
  if (_loadedCodex && _loadedCodex[nodeId]) return _loadedCodex[nodeId];
  return SPECIES_CODEX[nodeId] ?? null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Intervention result dialogue — AI-generated per-action flavour text
// AI_CONTENT: generated by CodeBuddy Genie / WorkBuddy
// ─────────────────────name───────────────────────────────────────────────────
const INTERVENTION_RESULT_DIALOGUE = {
  bioremediation: {
    Toxic:      "Bioremediation package deployed on this tile. The water clarifies slightly — a small victory in a toxic war.",
    Degraded:   "Bioremediators take hold here. If you targeted the source tile, stressor levels should drop noticeably by tomorrow.",
    Recovering: "The intervention supplements natural recovery on this tile. Stressor load is visibly declining.",
    Pristine:   "Almost unnecessary at this point — but thorough. Stressor suppressed on your current tile.",
  },
  rebalancing: {
    Toxic:      "Rebalancing intervention deployed under duress. Populations stabilise — barely.",
    Degraded:   "You redistribute resources across trophic levels. The food web breathes a little easier.",
    Recovering: "Rebalancing accelerates the recovery trajectory. Well timed.",
    Pristine:   "Fine-tuning a healthy system. Population dynamics are now near-optimal.",
  },
  stabilization: {
    Toxic:      "Site locked down. Stressor can no longer spike here — giving species on this tile a fighting chance.",
    Degraded:   "Stabilization anchors this tile. Effective carrying capacity rises as the stressor load drops to a safe ceiling.",
    Recovering: "A protected tile in a recovering biome amplifies the recovery signal. Species here should rebound faster.",
    Pristine:   "The tile is already clean — stabilization is mostly symbolic, but the protection marker stands.",
  },
};

/**
 * getInterventionDialogue(type, tier) → string
 *
 * @param {'bioremediation'|'rebalancing'|'stabilization'} type
 * @param {'Toxic'|'Degraded'|'Recovering'|'Pristine'} tier
 * @returns {string}
 */
export function getInterventionDialogue(type, tier) {
  const pool = INTERVENTION_RESULT_DIALOGUE[type];
  if (!pool) return "Intervention deployed.";
  return pool[tier] ?? pool.Degraded;
}

// ─────────────────────────────────────────────────────────────────────────────
// Intervention descriptions (shown in vendor panel)
// ─────────────────────────────────────────────────────────────────────────────
export const INTERVENTION_DESCRIPTIONS = {
  bioremediation: {
    name:   'Bioremediation',
    icon:   '🧪',
    effect: '−50 stressor on YOUR current tile',
    detail: 'Navigate to the polluted tile first, then deploy microbial agents. The right tile matters — this is the core deduction.',
  },
  rebalancing: {
    name:   'Trophic Rebalancing',
    icon:   '⚖️',
    effect: 'Reintroduce a native (if habitat clear) OR cull an invasive',
    detail: 'If a species is critically low on a clean tile (L<20), it is reintroduced to 20% capacity. Otherwise, the most over-abundant non-keystone species is culled by 30%.',
  },
  stabilization: {
    name:   'Site Stabilization',
    icon:   '🛡️',
    effect: 'Protect current tile — stressor capped at 20 (raises K)',
    detail: 'Stand on the tile you want to protect. Marks it stable: stressor locked ≤20, raising effective carrying capacity for species on that tile.',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Field Report — AI-generated end-of-run recap
// AI_CONTENT: deterministic assembly from report-fragments.json (fallback: inline)
// AI_MODULE_TAG: FIELD_REPORT
// ─────────────────────────────────────────────────────────────────────────────

/**
 * _pickFragment(key, seedIndex) → string
 *
 * Picks one variant from the loaded (or fallback) fragments pool for `key`.
 * Selection is deterministic: index = seedIndex % variants.length.
 *
 * @param {string} key        — e.g. 'win_fast', 'lesson_root_cause'
 * @param {number} seedIndex  — derived from state.meta.seed (no Math.random)
 * @returns {string}
 */
function _pickFragment(key, seedIndex) {
  const pool = _loadedFragments?.[key];
  if (pool && Array.isArray(pool) && pool.length > 0) {
    return pool[Math.abs(seedIndex) % pool.length];
  }
  // Inline fallback strings (used when JSON not loaded)
  const FALLBACK = {
    win_fast:             "Early stressor control compounded; the meadow is recovering ahead of schedule.",
    win_close:            "The margin was thin, but the wetland is standing — a narrow but legitimate restoration.",
    lose_timeout:         "Stressor loading persisted too long; cumulative trophic debt exceeded what the remaining window could repay.",
    lose_keystone:        "Once the apex node collapses the energy pyramid loses its regulatory ceiling — recovery without restocking is not viable.",
    lesson_root_cause:    "Suppressing the stressor at its source gave downstream species the clean-water window they needed.",
    lesson_symptom_only:  "Mid-trophic interventions slowed the decline but never addressed the source; symptom management without source control is a rearguard action against arithmetic.",
    lesson_deep_scan:     "Full edge resolution early converted ambiguous health readings into a ranked action list.",
    lesson_shallow_scan:  "Shallow survey confirmed presence/absence but the dependency edges remained invisible until it was too late.",
  };
  return FALLBACK[key] ?? '';
}

/**
 * _splicePlaceholders(template, vars) → string
 *
 * Replaces {days} {keystone} {stressor} {health} {edgePct} in a template string.
 * Unknown placeholders are left as-is.
 *
 * @param {string} template
 * @param {object} vars — map of placeholder name → value
 * @returns {string}
 */
function _splicePlaceholders(template, vars) {
  return template.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? vars[k] : `{${k}}`));
}

/**
 * getFieldReportFragment(state) → string
 *
 * Generates a deterministic end-of-run text summary.
 * Prose outcome + lesson lines come from report-fragments.json (loaded at boot).
 * Falls back to inline strings if the JSON was not loaded (Rule 01 offline safety).
 * Stats block (coverage, extinctions, day count, timer) is always computed live.
 *
 * Variant selection: deterministic index from state.meta.seed (NO Math.random).
 *
 * @param {object} state — GameState at end of run
 * @returns {string} multi-line report text
 */
export function getFieldReportFragment(state) {
  const { day_count, ecosystem_health, market_tier, collapse_timer, seed } = state.meta;
  const { win, lose } = state.flags;

  // ── Derived stats ─────────────────────────────────────────────────────────
  const discoveredCount = state.notebook.discovered_nodes
    .filter(id => state.world.nodes[id] && state.world.nodes[id].kind !== 'stressor').length;
  const revealedEdges   = state.notebook.revealed_edges.length;
  const totalNodes      = Object.values(state.world.nodes).filter(n => n.kind !== 'stressor').length;
  const totalEdges      = state.world.edges.length;

  const extinctList = Object.values(state.world.nodes)
    .filter(n => n.status === 'extinct')
    .map(n => n.name);
  const keystoneSurvived = Object.values(state.world.nodes)
    .filter(n => n.keystone && n.kind !== 'stressor')
    .every(n => n.status !== 'extinct');

  // First extinct keystone name (for {keystone} placeholder)
  const extinctKeystone = Object.values(state.world.nodes)
    .find(n => n.keystone && n.status === 'extinct');
  const keystoneName = extinctKeystone?.name ?? 'keystone species';

  // Primary stressor name (first stressor-kind node)
  const stressorNode = Object.values(state.world.nodes).find(n => n.kind === 'stressor');
  const stressorName = stressorNode?.name ?? 'agricultural runoff';

  // Edge coverage % (for lesson_deep_scan threshold)
  const edgePct = totalEdges > 0 ? Math.round((revealedEdges / totalEdges) * 100) : 0;

  // Mean stressor load across all tiles (to judge root-cause success)
  const tileStressors = Object.values(state.world.tiles).map(t => t.stressor ?? 0);
  const meanStressor  = tileStressors.length > 0
    ? tileStressors.reduce((a, b) => a + b, 0) / tileStressors.length
    : 100;

  // Was bioremediation ever used? Check via state flag or tile evidence
  const bioUsed = state.notebook.interventions_used?.includes('bioremediation') ?? meanStressor < 40;

  // Deterministic seed index for variant selection (no Math.random)
  const seedIdx = Math.abs(typeof seed === 'number' ? seed : 1);

  // ── Placeholder map ───────────────────────────────────────────────────────
  const vars = {
    days:     day_count,
    keystone: keystoneName,
    stressor: stressorName,
    health:   Math.round(ecosystem_health),
    edgePct:  edgePct,
  };

  // ── Outcome key selection ─────────────────────────────────────────────────
  // win_fast  : won with >8 days to spare on the 40-day timer
  // win_close : won but ≤8 days to spare
  // lose_keystone : a keystone is extinct
  // lose_timeout  : timer expired, no keystone extinct
  let outcomeKey;
  if (win) {
    outcomeKey = collapse_timer > 8 ? 'win_fast' : 'win_close';
  } else if (!keystoneSurvived) {
    outcomeKey = 'lose_keystone';
  } else {
    outcomeKey = 'lose_timeout';
  }

  // ── Lesson key selection ──────────────────────────────────────────────────
  // lesson_root_cause   : bioremediation was used AND final mean stressor is low (<35)
  // lesson_symptom_only : interventions used but stressor not resolved
  // lesson_deep_scan    : edge-reveal coverage ≥ 66%
  // lesson_shallow_scan : edge-reveal coverage < 66%
  let lessonKey;
  if (bioUsed && meanStressor < 35) {
    lessonKey = 'lesson_root_cause';
  } else if (edgePct >= 66) {
    lessonKey = 'lesson_deep_scan';
  } else if (bioUsed) {
    lessonKey = 'lesson_symptom_only';
  } else {
    lessonKey = 'lesson_shallow_scan';
  }

  // ── Pick and splice prose fragments ──────────────────────────────────────
  const outcomeProse = _splicePlaceholders(_pickFragment(outcomeKey, seedIdx),     vars);
  const lessonProse  = _splicePlaceholders(_pickFragment(lessonKey,  seedIdx + 7), vars);

  // ── Static stats block (always computed live) ─────────────────────────────
  const coveragePct   = totalNodes > 0 ? Math.round((discoveredCount / totalNodes) * 100) : 0;
  const investigation =
    `Investigation coverage: ${discoveredCount}/${totalNodes} species (${coveragePct}%), ` +
    `${revealedEdges}/${totalEdges} trophic links revealed.`;

  const extinctReport = extinctList.length > 0
    ? `Species lost: ${extinctList.join(', ')}.`
    : `No species extinctions recorded. ` + (keystoneSurvived ? 'All keystone species survived.' : '');

  const healthReport =
    `Final ecosystem health: ${Math.round(ecosystem_health)}% (${market_tier}). ` +
    `Day ${day_count}. Collapse timer remaining: ${Math.max(0, collapse_timer)} days.`;

  // ── Attribution badge (hackathon rubric: AI_CONTENT tag) ─────────────────
  const badge = `[ Generated by CodeBuddy Genie · AI_MODULE: FIELD_REPORT · seed ${seed} ]`;

  return [
    outcomeProse,
    '',
    lessonProse,
    '',
    investigation,
    extinctReport,
    healthReport,
    '',
    badge,
  ].join('\n');
}
